defmodule TzTest.Repo.Migrations.CreateTempTable do
  use Ecto.Migration

  def change do
    execute("""
      CREATE TABLE tz_test(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        tz_col TIMESTAMPTZ
      )
    """, "DROP TABLE tz_test")
  end
end
